apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    type: backend
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        type: backend
    spec:
      containers:
        - name: backend-container
          image: kumarm5/django_server
  replicas: 3
  selector:
    matchLabels:
      type: backend
